[application]
tailwind_input = "tailwind.css"
tailwind_output = "public/assets/tailwind.css"

[web.app]

# HTML title tag content
title = "RusTerm - High Performance Serial Monitor & Terminal"

# include `assets` in web platform
[web.resource]
style = ["assets/tailwind.css", "assets/css/xterm.css"]
script = ["assets/js/xterm.js", "assets/js/xterm-addon-fit.js"]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
